In [5]:
# 一个大的batch
x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]
w = 1.0   #随便选一个初始值
def forward(x):
    return x * w
def cost(xs, ys):
    cost = 0
    for x, y in zip(xs, ys): 
        y_pred = forward(x)
        cost += (y_pred - y) ** 2
    return cost / len(xs)
def gradient(xs, ys):
    grad = 0
    for x, y in zip(xs, ys):
        grad += 2 * x * (x * w - y)
    return grad / len(xs)
print('Predict (before training)', 4, forward(4)) 
for epoch in range(100):
    cost_val = cost(x_data, y_data)
    grad_val = gradient(x_data, y_data)
    w -= 0.01 * grad_val
    print('Epoch:', epoch, 'w=', w, 'loss=', cost_val)
    print('Predict (after training)', 4, forward(4))

Predict (before training) 4 4.0
Epoch: 0 w= 1.0933333333333333 loss= 4.666666666666667
Predict (after training) 4 4.373333333333333
Epoch: 1 w= 1.1779555555555554 loss= 3.8362074074074086
Predict (after training) 4 4.711822222222222
Epoch: 2 w= 1.2546797037037036 loss= 3.1535329869958857
Predict (after training) 4 5.0187188148148145
Epoch: 3 w= 1.3242429313580246 loss= 2.592344272332262
Predict (after training) 4 5.2969717254320985
Epoch: 4 w= 1.3873135910979424 loss= 2.1310222071581117
Predict (after training) 4 5.54925436439177
Epoch: 5 w= 1.4444976559288012 loss= 1.7517949663820642
Predict (after training) 4 5.777990623715205
Epoch: 6 w= 1.4963445413754464 loss= 1.440053319920117
Predict (after training) 4 5.9853781655017855
Epoch: 7 w= 1.5433523841804047 loss= 1.1837878313441108
Predict (after training) 4 6.173409536721619
Epoch: 8 w= 1.5859728283235668 loss= 0.9731262101573632
Predict (after training) 4 6.343891313294267
Epoch: 9 w= 1.6246153643467005 loss= 0.7999529948031382
Pred

In [9]:
import numpy as np
a=[1,2,3,4,5]
b=(1,2,3,4,5)
c=np.arange(5)
d="zhang"
print(list(zip(a,b,c,d)))   #可以去掉list看看出来的是啥

[(1, 1, 0, 'z'), (2, 2, 1, 'h'), (3, 3, 2, 'a'), (4, 4, 3, 'n'), (5, 5, 4, 'g')]


In [16]:

import torch
a = torch.tensor([1.0])
a.requires_grad = True # 或者 a.requires_grad_()
print(a)
print(a.data)
print(a.type())             # a的类型是tensor
print(a.data.type())        # a.data的类型是tensor
print(a.grad)
print(type(a.grad))
print(a.data.item())


tensor([1.], requires_grad=True)
tensor([1.])
torch.FloatTensor
torch.FloatTensor
None
<class 'NoneType'>
1.0


In [25]:
import torch
x_data = [1.0, 2.0, 3.0] 
y_data = [2.0, 4.0, 6.0]
w = torch.Tensor([1.0]) 
w.requires_grad = True
def forward(x):
    return x * w    
def loss(xs, ys):
    y = forward(xs)
    return (y-ys)**2
for epoch in range(100):
    for x, y in zip(x_data, y_data):
        l = loss(x, y)
        l.backward()
        w.data = w.data - 0.01 * w.grad.data
        w.grad.data.zero_() 
    print("progress:", epoch, l.item())
    print("w",w.data.item())
print("predict (after training)", 4, forward(4).item())


progress: 0 7.315943717956543
w 1.260688066482544
progress: 1 3.9987640380859375
w 1.4534177780151367
progress: 2 2.1856532096862793
w 1.5959051847457886
progress: 3 1.1946394443511963
w 1.7012479305267334
progress: 4 0.6529689431190491
w 1.779128909111023
progress: 5 0.35690122842788696
w 1.836707353591919
progress: 6 0.195076122879982
w 1.8792757987976074
progress: 7 0.10662525147199631
w 1.9107471704483032
progress: 8 0.0582793727517128
w 1.9340143203735352
progress: 9 0.03185431286692619
w 1.9512161016464233
progress: 10 0.017410902306437492
w 1.9639335870742798
progress: 11 0.009516451507806778
w 1.9733357429504395
progress: 12 0.005201528314501047
w 1.9802868366241455
progress: 13 0.0028430151287466288
w 1.9854258298873901
progress: 14 0.0015539465239271522
w 1.989225149154663
progress: 15 0.0008493617060594261
w 1.9920340776443481
progress: 16 0.00046424579340964556
w 1.9941107034683228
progress: 17 0.0002537401160225272
w 1.9956458806991577
progress: 18 0.00013869594840798527
w

In [26]:
## homework 我们写一个y=x^2+x+1的，一个两个节点的计算图,我们用y=ax^2+bx+c来拟合，a,b,c是需要计算梯度的
import torch 
learning_rate = 0.01
epochs = 100
# 训练集合
x_data = [1.0,2.0,3.0]
y_data = [3.0,7.0,13.0]
a = torch.Tensor([2.0])
b = torch.Tensor([2.0])
c = torch.Tensor([2.0])
a.requires_grad = True
b.requires_grad = True
c.requires_grad = True
# 定义前向传播函数
def forward(x):
    y = a*x*x + b*x + c
    return y
def loss(xs,ys):
    y_pred = forward(xs)
    return (ys-y_pred)**2
# 训练过程
for epoch in range(epochs):
    for x,y in zip(x_data,y_data):
        l = loss(x,y)
        l.backward()
        a.data = a.data -learning_rate * a.grad.data
        b.data = b.data -learning_rate * b.grad.data
        c.data = c.data -learning_rate * c.grad.data
        a.grad.data.zero_() 
        b.grad.data.zero_() 
        c.grad.data.zero_() 
    print("epoch", epoch, "loss:", l.item(), "a", a.data.item(), "b", b.data.item(), "c", c.data.item())


epoch 0 loss: 43.04933547973633 a 0.23258423805236816 b 1.283128023147583 c 1.6771759986877441
epoch 1 loss: 14.719114303588867 a 1.0675642490386963 b 1.5835927724838257 c 1.787113904953003
epoch 2 loss: 1.0651649236679077 a 0.6911706924438477 b 1.4119752645492554 c 1.6972432136535645
epoch 3 loss: 1.449332356452942 a 0.8779559135437012 b 1.4612475633621216 c 1.7018367052078247
epoch 4 loss: 0.01829000748693943 a 0.8022456169128418 b 1.4089248180389404 c 1.6639125347137451
epoch 5 loss: 0.3663938045501709 a 0.8482401967048645 b 1.4050121307373047 c 1.6471521854400635
epoch 6 loss: 0.1299343705177307 a 0.8371891975402832 b 1.3796687126159668 c 1.6218717098236084
epoch 7 loss: 0.20184975862503052 a 0.8522809147834778 b 1.3653489351272583 c 1.6018317937850952
epoch 8 loss: 0.14731234312057495 a 0.8548237085342407 b 1.3469113111495972 c 1.580580234527588
epoch 9 loss: 0.15293006598949432 a 0.8628348708152771 b 1.3313617706298828 c 1.5610716342926025
epoch 10 loss: 0.1335027515888214 a 0.86

tensor([[0., 0., 0.]])

In [ ]:
# 改写成向量的形式
import torch 
learning_rate = 0.01
epochs = 100
# 训练集合
x_data = [1.0,2.0,3.0]
y_data = [3.0,7.0,13.0]
a = torch.Tensor([2.0])
b = torch.Tensor([2.0])
c = torch.Tensor([2.0])
a.requires_grad = True
b.requires_grad = True
c.requires_grad = True
# 定义前向传播函数
def forward(x):
    y = a*x*x + b*x + c
    return y
def loss(xs,ys):
    y_pred = forward(xs)
    return (ys-y_pred)**2
# 训练过程
for epoch in range(epochs):
    for x,y in zip(x_data,y_data):
        l = loss(x,y)
        l.backward()
        a.data = a.data -learning_rate * a.grad.data
        b.data = b.data -learning_rate * b.grad.data
        c.data = c.data -learning_rate * c.grad.data
        a.grad.data.zero_() 
        b.grad.data.zero_() 
        c.grad.data.zero_() 
    print("epoch", epoch, "loss:", l.item(), "a", a.data.item(), "b", b.data.item(), "c", c.data.item())

In [32]:
#第五章用一种更具扩展性的写法来写神经网络
import torch
x_data = torch.Tensor([[1.0], [2.0], [3.0]]) 
y_data = torch.Tensor([[2.0], [4.0], [6.0]])
x_data.size()

torch.Size([3, 1])

In [38]:
import torch
# prepare dataset
# x,y是矩阵，3行1列 也就是说总共有3个数据，每个数据只有1个特征
x_data = torch.tensor([[1.0], [2.0], [3.0]])
y_data = torch.tensor([[2.0], [4.0], [6.0]])
 
#design model using class
"""
our model class should be inherit from nn.Module, which is base class for all neural network modules.
member methods __init__() and forward() have to be implemented
class nn.linear contain two member Tensors: weight and bias
class nn.Linear has implemented the magic method __call__(),which enable the instance of the class can
be called just like a function.Normally the forward() will be called 
"""
#定义model，需要补全forward函数
class LinearModel(torch.nn.Module):
    def __init__(self):
        super(LinearModel, self).__init__()
        # (1,1)是指输入x和输出y的特征维度，这里数据集中的x和y的特征都是1维的
        # 该线性层需要学习的参数是w和b  获取w/b的方式分别是~linear.weight/linear.bias
        self.linear = torch.nn.Linear(1, 1)
 
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred
# 实例化model
model = LinearModel()

# 都早优化器以及loss计算方式
# construct loss and optimizer
# criterion = torch.nn.MSELoss(size_average = False)
criterion = torch.nn.MSELoss(reduction = 'sum')
optimizer = torch.optim.SGD(model.parameters(), lr = 0.02) # model.parameters()自动完成参数的初始化操作
 
#训练过程 
# training cycle forward, backward, update
for epoch in range(100):
    y_pred = model(x_data) # forward:predict
    loss = criterion(y_pred, y_data) # forward: loss
    print(epoch, loss.item())
    loss.backward() # backward: autograd，自动计算梯度
    optimizer.step() # update 参数，即更新w和b的值
    optimizer.zero_grad() # the grad computer by .backward() will be accumulated. so before backward, remember set the grad to zero
print('w = ', model.linear.weight.item())
print('b = ', model.linear.bias.item())
 
x_test = torch.tensor([[4.0]])
y_test = model(x_test)
print('y_pred = ', y_test.data.item())

0 16.323488235473633
1 1.996829628944397
2 0.389644056558609
3 0.20513498783111572
4 0.17987234890460968
5 0.17255279421806335
6 0.1673685908317566
7 0.1625480055809021
8 0.15788967907428741
9 0.1533677577972412
10 0.14897528290748596
11 0.1447087675333023
12 0.14056460559368134
13 0.13653895258903503
14 0.1326284557580948
15 0.12883004546165466
16 0.12514051795005798
17 0.12155647575855255
18 0.11807529628276825
19 0.11469364911317825
20 0.11140885204076767
21 0.1082182377576828
22 0.10511907935142517
23 0.10210853815078735
24 0.09918436408042908
25 0.09634371101856232
26 0.09358447045087814
27 0.09090422093868256
28 0.08830098807811737
29 0.08577194809913635
30 0.08331549167633057
31 0.08092951774597168
32 0.07861165702342987
33 0.07636026293039322
34 0.07417342066764832
35 0.07204911857843399
36 0.06998582929372787
37 0.06798148900270462
38 0.06603450328111649
39 0.06414332985877991
40 0.062306277453899384
41 0.06052188575267792
42 0.058788638561964035
43 0.0571049228310585
44 0.055